### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by shagal-sajid** [onecentlin/laravel-adminer#1]
![screen shot 2018-08-31 at 11 12 10 am](https://user-images.githubusercontent.com/33257942/44894719-d5a04d00-ad0e-11e8-837b-6d2a6b4f17ae.png)

I have done everything as required, and the database is working properly for all other laravel projects 
I don't understand what went wrong

**Comment by onecentlin** [comment]
@icodetheworld  Please check your mysql socket path.
You may modify your `php.ini` and update correct path for `mysql.default_socket`

**Comment by onecentlin** [comment]
Check your current mysql socket with command:
`netstat -ln | grep -o -m 1 -E '\S*mysqld?\.sock'`

This command works while your MySQL or MariaDB is running.

For mac user using MAMP, for example, it will print out `/Applications/MAMP/tmp/mysql/mysql.sock`
