### ISSUE TITLE
adminer.php config file not publish

### ISSUE THREAD

**Issue by jazz7381** [onecentlin/laravel-adminer#14]
with command php artisan vendor:publish --provider="Onecentlin\Adminer\ServiceProvider" only publish adminer.css file and not publish the config file. i'm using laravel 8

**Comment by onecentlin** [comment]
@jazz7381 It did publish config file as well. May you try it again?

**Comment by onecentlin** [comment]
@jazz7381 which version are you using? `config/adminer.php` is added since v5.1.x
You may update composer package up to v5.1.x

**Comment by jazz7381** [comment]
i'm using "onecentlin/laravel-adminer": "4.7.7.1" and "laravel/framework": "^8.0",

**Comment by onecentlin** [comment]
@jazz7381 Hi, config file is avaiable since version 5.0.0, but not 4.7.x
