### ISSUE TITLE
Update to Adminer 4.7.1 and use less-password plugin

### ISSUE THREAD

**Issue by KinG-InFeT** [onecentlin/laravel-adminer#3]
Hi, 
can you update adminer to 4.7.1?
I have a ask, can i use plugin for less-password to connect DB without password?

thanks you

**Comment by mattsches** [comment]
+1 for updating Adminer to latest version.

**Comment by onecentlin** [comment]
@KinG-InFeT and @mattsches  laravel-adminer has been updated to 4.7.1, enjoy!!

**Comment by KinG-InFeT** [comment]
hi @onecentlin thank you for this update,
can i use plugin for less-password to connect DB without password?

**Comment by stephaniemartin** [comment]
maybe it is not the best answer, but you can comment out adminer/include/adminer.inc.php like this:
function login($login, $password) {
		/*
		if ($password == "") {
			return lang('Adminer does not support accessing a database without a password, <a href="https://www.adminer.org/en/password/"%s>more information</a>.', target_blank());
		}
		*/
		return true;
	}

NOTE: THIS IS FOR LOCALHOST ONLY, IF YOU PLAN TO DEVELOP IT ON YOUR OWN MACHINE.
it is not suitable for live server. 
i just tested it for mongodb only. dont know for other database.

**Comment by princejijk** [comment]
It is very simple:
1. Open the adminer.php (or the exact php file of your adminer) in any text editor.
2. Use the FIND command in your text editor and find the following string on the next line:
       login($ye,$F){if($F=="")return

3. Type anything like xyz in between the double quotes and save it.
That's all! Now, the problem solved.

Just watch this video: 
https://www.youtube.com/watch?v=b8W0TjEsAHQ

**Comment by KinG-InFeT** [comment]
thanks you
